project:
  type: website

website:
  title: "S&P 500 correlated with Economic Indicators"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



